Milestone 8 of my project
Dinma-Faith/Dinma-Portfolio.github.io pull request #6
Opened 2022-04-08 11:32 UTC by Dinma-Faith

**In this project;**

- I created another js file 
- Created my projects dynamically in js file
- Used for loops to loop through the objects and arrays.

You can leave a comment 
Thanks

2022-04-08 19:47 UTC, mahbubul14 requested changes
Hi @Dinma-Faith ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Check the comments under the review for more suggestions. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Descriptive PR title & description.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-08 19:47 UTC, mahbubul14 commented on style.css
> +    font-weight: 400;
- [ ] Do not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history. Please remove the inline comments from line 768.

2022-04-08 19:47 UTC, mahbubul14 commented on modal.js
> +  },
- [ ] Currently, your design is not matched with the Figma design (Desktop version). See the below screenshot about the space on the left, right, and bottom also. Please fix that.

- [ ] When it popup, the background should be blurred. Please work on that for both mobile and desktop versions. 

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![d2](https://user-images.githubusercontent.com/70483835/162511616-7b877d5d-205b-45f8-8151-88777645e690.png) | ![d1](https://user-images.githubusercontent.com/70483835/162511353-c77ae024-dfaf-45ef-aba2-7b44fb20812a.png)

- [ ] When clicking on the see project button,  the navbar is still there. Check the image below and fix it.

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![m1](https://user-images.githubusercontent.com/70483835/162515982-282dfe24-be0e-4e66-b29d-1a6e1d00e5c3.png) | ![m2](https://user-images.githubusercontent.com/70483835/162516009-e8ef951a-4208-4a6d-96e5-632631261bc2.png)

2022-04-09 16:03 UTC, aimemalaika approved these changes
Hi @Dinma-Faith , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-09 16:04 UTC, merged